version: '3.8'

services:
  extractor:
    image: coffee:latest
    restart: always
    build:
      context: .
    working_dir: /input-data-folder
    volumes:
      - ./src:/src
      - ./data:/data
      - ${DATA_FOLDER}:/input-data-folder
      - ${DATA_SERIES_FOLDER}:/data-series


  trainer:
    image: coffee:latest
    restart: always
    build:
      context: .
    command: python /src/ai/audio_trainer.py /data-series --epochs 60
    volumes:
      - ./src:/src
      - ./data:/data
      - ${DATA_SERIES_FOLDER}:/data-series

