version: '3.8'

services:
  extractor:
    image: coffee:latest
    restart: no
    build:
      context: .
    working_dir: /input-data-folder
    command: python /src/extractor.py --audio --video input.spec.json
    environment:
      - TESSDATA_PREFIX=/data/tesseract/tessdata
    volumes:
      - ./src:/src
      - ./data:/data
      - ${DATA_FOLDER}:/input-data-folder
      - ${DATA_SERIES_FOLDER}:/data-series
      - ${MODEL_FOLDER}:/model


  trainer:
    image: coffee:latest
    restart: no
    build:
      context: .
    command: python /src/ai/audio_trainer.py /data-series --epochs 60
    volumes:
      - ./src:/src
      - ./data:/data
      - ${DATA_SERIES_FOLDER}:/data-series
      - ${MODEL_FOLDER}:/model

  learning:
    image: coffee:latest
    restart: no
    build:
      context: .
    command: python /src/learning/training-test.py
    volumes:
      - ./src:/src
      - ./data:/data
      - ${DATA_SERIES_FOLDER}:/data-series

